[phases.setup]
run = "corepack enable && corepack prepare pnpm@latest --activate && node -v"

[phases.build]
run = "pnpm install && pnpm run build"

[phases.start]
run = "pnpm start"

[env]
NODE_VERSION = "22.x"